name: Apache Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Command via SSH
        uses: appleboy/ssh-action@master
        env:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
        with:
          script: "cd /var/www/cypheriel.codes/; sudo git pull -f; poetry install; sudo systemctl reload apache2"
