name: Apache Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: SCP Files
        uses: appleboy/scp-action@v0.0.1
        env:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
        with:
          source: "./"
          target: "/var/www/cypheriel.codes/"
          rm: true
          overwrite: true
      
      - name: Execute Command via SSH
        uses: appleboy/ssh-action@master
        env:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
        with:
          script: "poetry install; sudo systemctl reload apache2"
