name: Apache Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Command via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: "cd /var/www/cypheriel.codes/; sudo git pull; sudo pip install -r requirements.txt; sudo systemctl reload apache2"
